### ISSUE TITLE
Fix the Fetching Error

### ISSUE THREAD

**Issue by onnhyd** [sceary-expert/programming-quotes-generator#4]
## While fetching the quote from the Quotable API its showing this Error:
![image](https://user-images.githubusercontent.com/84634405/194809340-3b142f10-9d57-45d2-8cd3-1dfec5482065.png)
## However It' working absolutely fine when I am trying locally(in localhost:3000)
# Error Message: 
/favicon.ico:1          Failed to load resource: the server responded with a status of 404 ()
script.js:12 User Just Clicked The Button
script.js:13 Mixed Content: The page at 'https://programming-quotes-generator.netlify.app/' was loaded over HTTPS, but requested an insecure resource 'http://api.quotable.io/random'. This request has been blocked; the content must be served over HTTPS.
generateRandomQuote @ script.js:13
script.js:13          Uncaught (in promise) TypeError: Failed to fetch
    at HTMLButtonElement.generateRandomQuote (script.js:13:5)

**Comment by onnhyd** [comment]
@Satyakoidala can you fix this?

**Comment by Satyakoidala** [comment]
Hi @sceary-expert,

I can fix this. Please assign this one to me. I have the fix ready.

**Comment by Satyakoidala** [comment]
Hi @sceary-expert,

I have fixed the issue, here https://github.com/sceary-expert/programming-quotes-generator/pull/5. Please accept this as hacktoberfest-accepted.

Thanks!.
